// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6cBWfvbtAzLb75eHBO9g2lVdIbUY6aOc',
    appId: '1:751216866169:web:0b333f0941ca94bd9735a8',
    messagingSenderId: '751216866169',
    projectId: 'scholarnexus-ca0ef',
    authDomain: 'scholarnexus-ca0ef.firebaseapp.com',
    storageBucket: 'scholarnexus-ca0ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaIAxb-O83gBWuafYmHKLk14SbYEkrmhg',
    appId: '1:751216866169:android:543e964f8980b3639735a8',
    messagingSenderId: '751216866169',
    projectId: 'scholarnexus-ca0ef',
    storageBucket: 'scholarnexus-ca0ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAniR0xH6H4FzMAgC69a2AyXuA7exMxIOQ',
    appId: '1:751216866169:ios:91cad226bca2a4bc9735a8',
    messagingSenderId: '751216866169',
    projectId: 'scholarnexus-ca0ef',
    storageBucket: 'scholarnexus-ca0ef.appspot.com',
    iosBundleId: 'com.example.myPrg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAniR0xH6H4FzMAgC69a2AyXuA7exMxIOQ',
    appId: '1:751216866169:ios:91cad226bca2a4bc9735a8',
    messagingSenderId: '751216866169',
    projectId: 'scholarnexus-ca0ef',
    storageBucket: 'scholarnexus-ca0ef.appspot.com',
    iosBundleId: 'com.example.myPrg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6cBWfvbtAzLb75eHBO9g2lVdIbUY6aOc',
    appId: '1:751216866169:web:4aa2d4b21ebe84679735a8',
    messagingSenderId: '751216866169',
    projectId: 'scholarnexus-ca0ef',
    authDomain: 'scholarnexus-ca0ef.firebaseapp.com',
    storageBucket: 'scholarnexus-ca0ef.appspot.com',
  );

}